services:
  - docker

jobs:
  include:
    - stage: secrets-scanning
      script: docker run -v $(pwd):/app thefriendlypirate/trufflehog ls -la /app
      name: "trufflehog"
    - script: docker run -v ${pwd}:/app thefriendlypirate/git-secrets ls -la /app
      name: "git-secrets"
