services:
  - docker

jobs:
  include:
    - stage: secrets-scanning
      script: docker run -v $(pwd):/app thefriendlypirate/git-secrets /bin/bash -c "cd /app && git secrets --scan"
      name: "git-secrets"
    - script: docker run -v $(pwd):/app thefriendlypirate/trufflehog trufflehog --json --max_depth 1 /app | jq .
      name: "trufflehog"
