services:
  - docker

jobs:
  include:
    - stage: secrets-scanning
      script: docker run -v $(pwd):/app thefriendlypirate/git-secrets run --from=travis-ci
      name: "git-secrets"
    - script: docker run -v $(pwd):/app -e TRUFFLEHOG_EXCLUSION_PATHS_FILE thefriendlypirate/trufflehog run --from=travis-ci
      name: "trufflehog"
      env:
        - TRUFFLEHOG_EXCLUSION_PATHS_FILE=${TRUFFLEHOG_EXCLUSION_PATHS_FILE:-trufflehog.ignore}
