services:
  - docker

jobs:
  include:
    - stage: secrets-scanning
      script: docker run -v $(pwd):/app ${SEC_GITSECRETS_IMAGE} run --from=travis-ci
      name: "git-secrets"
      env:
        - SEC_GITSECRETS_IMAGE=${SEC_GITSECRETS_IMAGE-thefriendlypirate/git-secrets:latest}
    - script: docker run -v $(pwd):/app -e TRUFFLEHOG_EXCLUSION_PATHS_FILE ${SEC_TRUFFLEHOG_IMAGE} run --from=travis-ci
      name: "trufflehog"
      env:
        - SEC_TRUFFLEHOG_IMAGE=${SEC_TRUFFLEHOG_IMAGE:-thefriendlypirate/trufflehog:latest}
        - TRUFFLEHOG_EXCLUSION_PATHS_FILE=${TRUFFLEHOG_EXCLUSION_PATHS_FILE:-trufflehog.ignore}
