services:
  - docker

jobs:
  allow_failures:
    - if: env(ALLOW_FAILURES) != false
  include:
    - stage: container-scanner
      script: docker run -e DOCKLE_INSECURE -e DOCKLE_USE_PRIVATE_REGISTRY -e DOCKLE_REGISTRY -e DOCKLE_REGISTRY_USER -e DOCKLE_REGISTRY_PASSWORD -e DOCKLE_IMAGE_URL thefriendlypirate/dockle run --from=travis-ci
      install: skip
      name: "dockle"
#    - script: docker run thefriendlypirate/trivy run --from=travis-ci
#      install: skip
#      name: "trivy"
