env:
  - TRUFFLEHOG_EXCLUSION_PATHS_FILE="trufflehog.ignore"

services:
  - docker

jobs:
  include:
    - stage: secrets-scanning
      script: export && touch 123 && ls -la
#      script: docker run -v $(pwd):/app thefriendlypirate/git-secrets run --from=travis-ci
      name: "git-secrets"
    - script: docker run -v $(pwd):/app thefriendlypirate/trufflehog run --from=travis-ci
      name: "trufflehog"
