services:
  - docker

jobs:
  allow_failures:
    - if: env(ALLOW_FAILURES) != false
  include:
    - stage: dast
      script: docker run -v $(pwd):/app thefriendlypirate/kubesec run --from=travis-ci
      install: skip
      name: "kubesec"
      if: env(USE_KUBESEC) == true
#    - script: docker run -v $(pwd):/app thefriendlypirate/zaproxy run --from=travis-ci
#      install: skip
#      name: "zaproxy"
