services:
  - docker

jobs:
  include:
    - stage: secrets-scanning
      - script: docker run thefriendlypirate/trufflehog pwd
        name: "trufflehog"
      - script: docker run thefriendlypirate/git-secrets pwd
        name: "git-secrets"
