language: node_js

import:
  - .secrets-scanning.yml

stages:
  - secrets-scanning
  - sca
  - sast
  - build
  - container-scanning
  - deploy
  - dast

jobs:
  include:
    - stage: build
      script: echo "build"
    - stage: deploy
      script: echo "deploy"
