language: node_js

env:
  - DOCKER_IMAGE_URL="thefriendlypirate/testssl:latest" SEC_DAST_TARGET_URL="https://node-api.pwc.delivery"
#  - DOCKLE_IMAGE_URL="thefriendlypirate/testssl"
#  - NO_INTERNET=true SEC_DAST_TARGET_URL="https://node-api.pwc.delivery"
#  - USE_ZAPROXY=true SEC_DAST_TARGET_URL="https://node-api.pwc.delivery"
#  - USE_KUBESEC=true
#  - USE_VERACODE=true

import:
  - .security-secrets-scanning-template.yml
  - .security-sca-template.yml
  - .security-sast-template.yml
  - .security-container-scanning-template.yml
  - .security-dast-template.yml

stages:
  - secrets-scanning
  - sca
  - sast
  - build
  - container-scanning
  - dast

jobs:
  include:
    - stage: build
      install: skip
      script: echo "build"
