language: ruby

import:
  - .security-secrets-scanning-template.yml
  - .security-sca-template.yml
  - .security-sast-template.yml
  - .security-container-scanning-template.yml
  - .security-dast-template.yml

stages:
  - secrets-scanning
  - sca
  - sast
  - build
  - container-scanning
  - deploy
  - dast

jobs:
  include:
    - stage: build
      script: echo "build"
    - stage: deploy
      script: echo "deploy"
