language: ruby

import:
  - .secrets-scanning-template.yml
  - .sca-template.yml
  - .sast-template.yml
  - .container-scanning-template.yml
  - .dast-template.yml

stages:
  - secrets-scanning
  - sca
  - sast
  - build
  - container-scanning
  - deploy
  - dast

jobs:
  include:
    - stage: build
      script: echo "build"
    - stage: deploy
      script: echo "deploy"
